In [ ]:
#here we start working with arrays in numpy

import numpy as np

In [ ]:
#creating a one dimention array with numpy

a1 = np.array(['Python','Hadoop','Numpy','R'])
a1

In [ ]:
#checking the size of the array
print(a1.shape)

In [ ]:
#checking the dimention of the array
print(a1.ndim)

In [ ]:
#creating a 2 dimentions array
a2 = np.array([['Altura','Largura','Profundidade'],[20,30,40]])
a2

In [ ]:
#cheking the shape of the array (2 linhas e 3 colunas)
a2.shape

In [ ]:
#checking the dinention of the array (2 dimentions)
a2.ndim

In [ ]:
#creating an array with 3 dimentions 
a3 = np.array([[10,15,18],[20,30,40],[45,87,90]])
a3

In [ ]:
#checking the shape of the array (3 linhas x 3 colunas)
a3.shape

In [ ]:
#checking the dimention of the array
#Notice that this is still a 2 dimention array. this is because we have 3 lines x 3 columns or (x and y)
a3.ndim

In [ ]:
#generalrule when to use parenthesis
#with parenthesis the method reflects an action to take
#withou parenthesis the method freflects a caracteristic of the element


In [ ]:
#returns the max element in an array - it needs to calculate the highest value in the array
a3.max()

In [ ]:
#it does not calculate anything. it just return a characteristic of the arrray
a3.ndim

In [ ]:
#useing the method arrange to create arrays in numpy
#creates an array from 0 to 19 (20 items)
array_1  = np.arange(20)
array_1

In [ ]:
#creating an array with numpy from 0 to 100, couting every 10 numbers (10 items)
array_2 = np.arange(0,100,10)
array_2

In [ ]:
#useing linspace to create arrays
#creating an vector from 0 to 100 with 20 items
matrix_1 = np.linspace(0,100,20)
matrix_1

In [ ]:
#now we create a vector from 0 to 10 with 20 items
matrix_2 = np.linspace(0,10,20)
matrix_2

In [ ]:
#now we create a matrix from 0 to 5 with 4 items
matrix_3 = np.linspace(0,5,4)
matrix_3

In [ ]:
#dynamically creating matrix structures
#creates a matrix 10 x 10 with zeroes
matrix_4 = np.zeros((10,10))
matrix_4

In [ ]:
#creating a matrix 3x3 with ones
matrix_5 = np.ones((3,3))
matrix_5

In [ ]:
#creating an identity matrix 10 x 10 with all ones on the main diagonal and zeros on the superior and iferior triangles
matrix_6 = np.eye(10)
matrix_6

In [ ]:
#creating a matrix passing the number of the mais diagonal
#the size of the matrix will be calculated based on the size of the diagonal, since the diagonal always tells
#us how many comuns and rows a matrix has
matrix_7 = np.diag((10,20,30,40,50,60,70,80,90))
matrix_7

In [ ]:
#creates an empty array but definning the shape and dimention
matrix_8 = np.empty((5,10))
matrix_8

In [ ]:
#tileing arrays
#this replicates each of the 3 arrays 2 times on the horizontal and 4 times on the vertical
matrix_9 = np.tile(np.array([[1,2],[3,4],[4,5]]),(2,4))
matrix_9

In [ ]:
#working with data types in arrays
#by default numpy creates an array based on the data type that is passe with the enphasis on the most specific type
#however you can tell it the data type you wanto on the array independent of the values passes as long as 
#they are compatible
array_1 = np.array([10,20,30],dtype='float')
array_1


In [ ]:
array_1.dtype

In [ ]:
array_2 = np.array([10,20,30.5])
array_2

In [ ]:
array_2.dtype

In [ ]:
array_3 = np.array([10,20,30])
array_3

In [ ]:
array_3.dtype


In [ ]:
#casting arrays - changing arrays data types
array_4 = np.array([10,20,40.5])
array_4.dtype

In [ ]:
array_4 = array_4.astype(int)
array_4.dtype

In [ ]:
array_4

In [ ]:
#array with aritimatic operations and arrange funcion
array_5 = np.arange(0,10) * 10
array_5

In [ ]:
array_6 = np.arange(0,10) ** 2
array_6

In [ ]:
#aritimatic operations with arrays
array_1 = np.arange(0,10)
array_2 = np.arange(0,10)+1
print(array_1)
print(array_2)

In [ ]:
#adding arrays
array_1 + array_2

In [ ]:
#subtracting arrays
array_1 - array_2

In [ ]:
#mutiplying arrays
array_1 * array_2

In [ ]:
#dividing arrays
array_1 / array_2

In [ ]:
#comparring arrays
array_1 == array_2

In [ ]:
#operating logical boolean table arrays with and / or
array_3 = np.array([True,False,True,False])
array_4 = np.array([False,False,True,False])

In [ ]:
np.logical_or(array_3,array_4)

In [ ]:
np.logical_and(array_3,array_4)

In [ ]:
#hadmart multioplication of matrix
array_5 = np.array([1,2,4])
array_6 = np.array([5,6,7])
array_5 * array_6

In [ ]:
#DOT PRODUCT mutiplication of matrixes
np.dot(array_5,array_6)

In [ ]:
#copying arrays
#becarefull with this type of copy that just creates a reference between arrays
array_7 = np.arange(0,10)
array_7

In [ ]:
#only creates a reference between the arrays
array_8 = array_7[5:]
array_8

In [ ]:
#fills the array with zero
array_7[:] = 0
array_7

In [ ]:
#now look what happens with array_8
array_8

In [ ]:
#to really copy the items of an array without the reference from the copied array we must use the method copy
array_7 = np.arange(0,10)
array_7

In [ ]:
array_8 = array_7[5:].copy()
array_8

In [ ]:
#now if i zero the array_7 the array_8 mantain its values
array_7[:] = 0
array_7

In [ ]:
#kept its values
array_8

In [1]:
#now we will work with arrays in numpy and its indexes
import numpy as np
array_1 = np.array([2,6,8,12,18,0])
array_1

array([ 2,  6,  8, 12, 18,  0])

In [2]:
#brings all the items in the array starting from the index 2 (third item because the index starts from 0)
array_1[2:]

array([ 8, 12, 18,  0])

In [3]:
#we can retrieve items stepping a specific numer of items
array_1[:5:2]

array([ 2,  8, 18])

In [15]:
#i can retrieve a specific item starting to count from the end -5 items
#([ 2,  6,  8, 12, 18,  0])
array_1[-5]

6

In [7]:
#i can retrieve all items from the -5th element to the end
array_1[-5:]

array([ 6,  8, 12, 18,  0])

In [10]:
#here is a cool way to invert the array
#here we get the entire array and start to retrieve the items in it from the last to the first item
array_1[::-1]


array([ 0, 18, 12,  8,  6,  2])

In [12]:
#here i can copy "by reference" some items of the array
array_2 = array_1[3:5]
array_2

array([12, 18])

In [14]:
#here i concatenate one array_3 (which is a reference of array_1 with 2 items) with array_1 inverted
array_3 = np.concatenate([array_2,array_1[::-1]])
array_3

array([12, 18,  0, 18, 12,  8,  6,  2])

In [17]:
#we will work with mutidimantional arrays indexing in numpy
array_4 = np.array([[1,2,3,4],[5,6,7,8],[10,20,30,40],[50,60,70,80]])
array_4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

In [19]:
#retrieveing a line
array_4[2]

array([10, 20, 30, 40])

In [22]:
#retrieveing a specific item where 0 is the lane and 2 is the column
array_4[0,2]

3

In [24]:
#now we can retrieve a range of numers from a specific line
#note that the last numer of the range is always exclusive
array_4[2,1:3]

array([20, 30])

In [26]:
#the same thing with colums
array_4[1:,3]

array([ 8, 40, 80])

In [27]:
array_4[-1,-1]

80

In [28]:
#writing to the array in a specific spot
array_4[0,0] = 0
array_4

array([[ 0,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

In [32]:
#checking the dimentions of the array
np.ndim(array_4)

2

In [38]:
#creating mutidimentional arrays 
array_5 = np.array([[[1,2],[10,20]],[[3,4],[30,40]],[[5,6],[50,60]]])
np.ndim(array_5)

3

In [39]:
array_5

array([[[ 1,  2],
        [10, 20]],

       [[ 3,  4],
        [30, 40]],

       [[ 5,  6],
        [50, 60]]])

In [40]:
np.shape(array_5)

(3, 2, 2)

In [41]:
array_5 * array_5

array([[[   1,    4],
        [ 100,  400]],

       [[   9,   16],
        [ 900, 1600]],

       [[  25,   36],
        [2500, 3600]]])

In [43]:
#working with matrixes in numpy
#matrixes can only have two dimentions
matrix_6 = np.matrix([[1,2],[3,4]])
matrix_6

matrix([[1, 2],
        [3, 4]])

In [ ]:
matrix_6 * matrix_6

In [46]:
matrix_7 = np.matrix([[2,3],[4,5]])
matrix_7

matrix([[2, 3],
        [4, 5]])

In [48]:
matrix_6 * matrix_7

matrix([[10, 13],
        [22, 29]])

In [49]:
matrix_6 + matrix_7

matrix([[3, 5],
        [7, 9]])

In [50]:
matrix_6 - matrix_7

matrix([[-1, -1],
        [-1, -1]])

In [52]:
#another way to mutiply matrixes is index by index
#the result is very diferent than the mutiplication with the operator
np.multiply(matrix_6,matrix_7)

matrix([[ 2,  6],
        [12, 20]])

In [54]:
#inverting matrixes or arrays
np.linalg.inv(matrix_6)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [58]:
#transposing arrays or matrixes
print(matrix_6)
print(matrix_6.T)

print('################')

print(array_5)
print(array_5.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
################
[[[ 1  2]
  [10 20]]

 [[ 3  4]
  [30 40]]

 [[ 5  6]
  [50 60]]]
[[[ 1  3  5]
  [10 30 50]]

 [[ 2  4  6]
  [20 40 60]]]


In [68]:
#boradcasting arrays two dimentional arrays
array_8 = np.array([[100,200,300]])
array_8

array([[100, 200, 300]])

In [69]:
np.ndim(array_8)

2

In [70]:
array_8.T

array([[100],
       [200],
       [300]])

In [71]:
#broadcasting the array is transposing the array and adding the items of the original array with the values 
#of the same array transposed
array_8.T + array_8

array([[200, 300, 400],
       [300, 400, 500],
       [400, 500, 600]])

In [89]:
#converting matrix in array
array_9 = np.array([np.arange(0,100,10),np.arange(100,200,10)])
array_9

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140, 150, 160, 170, 180, 190]])

In [90]:
np.shape(array_9)

(2, 10)

In [91]:
#converts the matrix in a vector
array_9.ravel()

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190])

In [92]:
#converting the matrix transposed into a vector
array_9.T.ravel()

array([  0, 100,  10, 110,  20, 120,  30, 130,  40, 140,  50, 150,  60,
       160,  70, 170,  80, 180,  90, 190])

In [95]:
#creating a random array from a range specifying the square size
array_10 = np.random.randint(1,30, size = (4,4))
array_10

array([[ 6,  8,  7, 16],
       [ 2, 18, 11, 18],
       [ 1,  2, 16,  1],
       [22,  1, 27, 19]])

In [98]:
#checks to see if any condition is met in the array
np.any((array_10 % 7) == 0)

True

In [100]:
#check if all conditions are met inside the array
np.all(array_10 < 26)

False

In [101]:
#reshaping arrays
array_11 = np.arange(1,16)
array_11

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [115]:
#creates an array with two dimentions 3,5 from the vector
array_12 = array_11.reshape(3,5)
array_12

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [116]:
array_12 = array_12[::-1]
array_12

array([[11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [118]:
#sorting the vector
#axis 0 is columns and axis 1 are the lines
array_12.sort(axis = 0)
array_12

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])